#INTEGRANTES E RA
#Breno Baldovinotti 		| 14315311
#Caroline Gerbaudo Nakazato 	| 17164260
#Marco Antônio de Nadai Filho 	| 16245961
#Nícolas Leonardo Külzer Kupka  | 16104325
#Paulo Mangabeira Birocchi 	| 16148363

obj-y := crypto_ecb.o read_write.o
